### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by ratiotile** [neumond/pybrood#1]
Problem after pip install:

    Traceback (most recent call last):
      File "example.py", line 2, in <module>
        from pybrood import BaseAI, run, game, Color
      File "F:\Projects\Starcraft AI\workspace\pybrood test\bot\pybro\lib\site-packages\pybrood\__init__
    .py", line 1, in <module>
        from .inner import *
    ImportError: DLL load failed: The specified procedure could not be found.

Looks like the error when the compiler is the wrong version. So I'll try to compile from source.

It looks like bwapi/include/BWAPI/SetContainer.h:54 is one line too far - it should be line 53.
I have bwapi tag=v4.1.2 checked out.

Should say "Setup paths in generator/config.py"

To build, requires `pip install jinja2 pyaml`

pybind path in config doesn't do anything, as the comment indicates
need to put pybind in right place, ..\pybind11-2.0.0\include\pybind11

had to change line  58 of inner.vcxproj to:

    <AdditionalIncludeDirectories>C:\Python35\include;..\..\pybind11-2.0.0\include;..\..\bwapi\bwapi\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>

Now the example works, I'm wondering what the difference is in the precompiled version?

I'm using `Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32`

**Comment by neumond** [comment]
Thanks for report. Python has some guards when loading compiled DLLs. One thing I remember is that I used 3.5.2. I guess compiler is MSC v.1900 too, but need to recheck this. I have plans to add more supported python versions with some automated tests. Will take a closer look slightly later.

**Comment by neumond** [comment]
Well, comment regarding pybind wasn't exactly about what you have thought. Made more explanation comments in config.py.

**Comment by neumond** [comment]
Incredible.. Packing a wheel under windows alters .pyd file.

**Comment by neumond** [comment]
Consider upgrading to 0.9.1
Just tested it with 3.5.1, 3.5.2, 3.5.3 and even added 3.6.0 support

**Comment by ratiotile** [comment]
Yes, it works now. What was the problem?

**Comment by neumond** [comment]
Use `pip wheel .` instead `setup.py bdist_wheel` under windows. Somehow bdist_wheel damages files while packing a wheel. Or may be I'm doing something wrong, but no idea what exactly, attaching files via package_data shouldn't cause such troubles.
