### ISSUE TITLE
Unresolved reference 'game' Warning in PyCharm

### ISSUE THREAD

**Issue by JasperGeurtz** [neumond/pybrood#3]
The example code works fine, but PyCharm gives the warning `Unresolved reference 'game'`

![warning](https://user-images.githubusercontent.com/10107858/27791190-24d80534-5ff4-11e7-9977-e29c7ac46c85.png)

Furthermore if I want to "compile" the code using cython, I get
```
Error compiling Cython file:
------------------------------------------------------------
...
        units = game.getAllUnits()
        for u in units:
            print('Unit', u.getID(), u.getType().getName(), u.getPosition(),
                  u.getTilePosition())

        game.print('Hello world!')
            ^
------------------------------------------------------------

example.py:17:13: Expected an identifier
```

Removing the line lets cython compile the file correctly.

Not sure if this is intended (might be an implementation thing), but I just put this information here as an issue as it might be useful.

For now I just don't use cython and ignore PyCharm. Thank you for pybrood!

**Comment by neumond** [comment]
@JasperGeurtz Hello, did you solve the problem?

**Comment by JasperGeurtz** [comment]
@neumond No I didn't, but it's not a pybrood issue (I think), so I closed it

**Comment by ghost** [comment]
If it is pycharm issue, can you tell us how to solve it in pycharm?
If you did solve it.

**Comment by JasperGeurtz** [comment]
I disabled the warning/inspection using this:
https://www.jetbrains.com/help/pycharm/disabling-and-enabling-inspections.html
